### ISSUE TITLE
Source address for FORWARD / STUB

### ISSUE THREAD

**Issue by felbinger** [CZ-NIC/knot-resolver#120]
Is it possible to specify the source address for forward / stub policies? 
```
policy.add(policy.suffix(policy.STUB({
  '172.20.0.53',
  '172.23.0.53',
  'fd42:d42:d42:54::1',
  'fd42:d42:d42:53::1'
}), {todname('dn42.')}))
```
I couldn't find anything in the documentation yet.

**Comment by felbinger** [comment]
Thanks a lot

**Comment by felbinger** [comment]
@vcunat Is it possible to use these outgoing addresses only for a specific policy?

**Comment by vcunat** [comment]
No, currently this is the only setting we have.

**Comment by felbinger** [comment]
Ok, so NAT it's going to be 😒 Thank you!
