### ISSUE TITLE
Debian packages to install to compile the resolver

### ISSUE THREAD

**Issue by bortzmeyer** [CZ-NIC/knot-resolver#15]
May be a welcome addtion to the documentation in http://knot-resolver.readthedocs.org/en/latest/build.html

For Debian unstable, alias "sid"

libknot-dev libuv1-dev libcmocka-dev libluajit-5.1-dev

**Comment by vavrusa** [comment]
Added Debian/openSUSE/OS X in 57ea7b8 (though the list is incomplete).
