### ISSUE TITLE
[apparmor] local include support

### ISSUE THREAD

**Issue by darix** [CZ-NIC/knot-resolver#22]
```
diff --git a/scripts/kresd.apparmor b/scripts/kresd.apparmor
index 81fa5a1..8ad4c26 100644
--- a/scripts/kresd.apparmor
+++ b/scripts/kresd.apparmor
@@ -26,5 +26,7 @@
   /usr/lib{,64}/kdns_modules/tinyweb/ r,
   /usr/lib{,64}/kdns_modules/tinyweb/* r,
   /var/lib/GeoIP/* r,
+  # Site-specific additions and overrides. See local/README for details.
+  #include <local/usr.bin.kresd>
 }
```

I just noticed my kresd apparmor profile referenced my dnsdist local file. anyway... having those local includes in the end means user can adapt the profile for local needs while having the main profile under distribution control. not sure if we want to have an install target for the apparmor profile as well.

**Comment by vavrusa** [comment]
Thanks!
