### ISSUE TITLE
Feature request: module rewriting domain name

### ISSUE THREAD

**Issue by lonewolf1764** [CZ-NIC/knot-resolver#26]
**Problem**
We need module, which is able to combine blocking and rewriting. It should be based on source IP and destination at domain name.

**Comment by vavrusa** [comment]
Thank you for writing in! Can you expand it a little bit so I have something to hold onto?
For example:
* What is the ultimate goal, what are you trying to achieve
* How many block rules
* How would you expect to use it (mock configuration snippet)

**Comment by vavrusa** [comment]
You might find https://github.com/CZ-NIC/knot-resolver/wiki/HTTP-2-interface-&-DNS-firewall#dns-firewall interesting, it should support what you need.

**Comment by vavrusa** [comment]
Closing.
