### ISSUE TITLE
Images for Wiki (changelog)

### ISSUE THREAD

**Issue by vavrusa** [CZ-NIC/knot-resolver#27]
![http_ex1](https://cloud.githubusercontent.com/assets/139311/16609021/6bb86190-4305-11e6-8c6d-8844e064b91c.gif)
![http_ex2](https://cloud.githubusercontent.com/assets/139311/16609024/6bc03636-4305-11e6-90f0-bf812eaaa881.gif)
![http_ex3](https://cloud.githubusercontent.com/assets/139311/16609022/6bbc4c10-4305-11e6-95bb-76c3a7e9309c.gif)
![http_ex4](https://cloud.githubusercontent.com/assets/139311/16609023/6bbe61b2-4305-11e6-986c-cf91c5ce0fff.gif)

**Comment by pspacek** [comment]
@vavrusa It is not clear what this issue means. Please clarify it :-)
