### ISSUE TITLE
Clearing the cache at startup

### ISSUE THREAD

**Issue by paulehoffman** [CZ-NIC/knot-resolver#31]
Adding `cache.clear()` to the beginning or end of the config file doesn't seem to clear the cache, while entering it at the command line does. I have a use case where I want the cache cleared each time the daemon is started.

**Comment by vavrusa** [comment]
The cache is not active in configuration until you open it (and if you don't, it will be opened afterwards if it wasn't closed explicitly in the config). You can either create ephemeral working directories for running instances to get docker-like behaviour, or configure cache explicitly:

```lua
cache.size = 10*MB -- Or with path: cache.open(10*MB, '/tmp/path')
cache.clear()
```

**Comment by paulehoffman** [comment]
Yes, that works. Thanks!
