### ISSUE TITLE
cache prefers parent-side TTL to authoritative

### ISSUE THREAD

**Issue by vcunat** [CZ-NIC/knot-resolver#34]
Reported [on ML](https://lists.nic.cz/pipermail/knot-dns-users/2016-November/000980.html).

Knot Resolver seems to cache the TTL of parent zone (= delegation) instead
of the TTL which is in the zone itself.

```
dig +noall +auth @n.ns.at univie.ac.at ns 
univie.ac.at.		10800	IN	NS	ns3.univie.ac.at.
univie.ac.at.		10800	IN	NS	ns4.univie.ac.at.
univie.ac.at.		10800	IN	NS	ns5.univie.ac.at.
univie.ac.at.		10800	IN	NS	ns7.univie.ac.at.
univie.ac.at.		10800	IN	NS	ns8.univie.ac.at.
univie.ac.at.		10800	IN	NS	ns10.univie.ac.at.
```
```
dig +noall +ans @ns10.univie.ac.at univie.ac.at ns
univie.ac.at.		600	IN	NS	ns7.univie.ac.at.
univie.ac.at.		600	IN	NS	ns4.univie.ac.at.
univie.ac.at.		600	IN	NS	ns8.univie.ac.at.
univie.ac.at.		600	IN	NS	ns3.univie.ac.at.
univie.ac.at.		600	IN	NS	ns5.univie.ac.at.
univie.ac.at.		600	IN	NS	ns10.univie.ac.at.
```
```
dig +noall +ans @ns10.univie.ac.at ns10.univie.ac.at a
ns10.univie.ac.at.	600	IN	A	192.76.243.2
```

Knot Resolver is caching 10800 instead of 600:

```
dig +noall +answer @127.0.0.1 ns10.univie.ac.at a
ns10.univie.ac.at.	10634	IN	A	192.76.243.2
```

Bind, unbound and pdns-recursor cache authoritative TTL (600).

**Comment by oerdnj** [comment]
There has been discussion at DNS-OARC brought by Fujiwara-san about parent-centric behaviour, and there's a draft now: https://tools.ietf.org/html/draft-fujiwara-dnsop-resolver-update-00

I was initially opposed to the idea, because I think it will just create more craziness in the DNS, but I am still in the phase of investigating how much will things break.

Nominum is also parent-centric for several years now without any significant breakages, and this would make the resolver job much more deterministic.

**Comment by vcunat** [comment]
Is there some reference to use cases for the parent-side and child-side records being different? The child-side TTLs tend to be lower but what is it good for? Otherwise I see only https://tools.ietf.org/html/draft-fujiwara-dnsop-resolver-update-00#ref-DUAN2012GHOST

**Comment by oerdnj** [comment]
The usual (old) approach would be to use the parent NS records only for bootstrapping and replace those with child-side NS records.

That way you can quickly test new deployed NS before pushing the change into parent. Or modify the TTL in case you plan to move your domain between DNS providers.

Also see Stephane's comment here: https://mailarchive.ietf.org/arch/msg/dnsop/1ESN4Uo8BRGrkadS-YXFR3z_cx0 and my here: https://mailarchive.ietf.org/arch/msg/dnsop/43WBzmkVoFWkWdSCCJ42nyQuY1k

**Comment by oerdnj** [comment]
This basically calls for having two separate caches - a delegation and record cache. And we can have an option whether the records from record cache should overwrite matching records in the delegation cache?

Would it be feasible?

**Comment by vcunat** [comment]
Hmm, currently resolver does prefer child-side record if in strict mode:
```
mode('strict')
```

I'm getting a strange SERVFAIL on the first attempt when validating, but it goes OK on subsequent cached ones (or when not validating).

```
[plan] plan 'ns10.univie.ac.at.' type 'A'
[resl]   => using root hints
[plan]   plan '.' type 'DNSKEY'
[resl]     => querying: '2001:dc3::35' score: 10 zone cut: '.' m12n: '.' type: 'DNSKEY' proto: 'udp'
[iter]     <= rcode: NOERROR
[vldr]     <= parent: updating DNSKEY
[vldr]     <= answer valid, OK
[resl]     <= server: '2001:dc3::35' rtt: 30 ms
[resl]   => querying: '202.12.27.33' score: 10 zone cut: '.' m12n: 'AT.' type: 'NS' proto: 'udp'
[resl]   => querying: '2001:500:9f::42' score: 10 zone cut: '.' m12n: 'AT.' type: 'NS' proto: 'udp'
[iter]   <= using glue for 'j.ns.at.'
[iter]   <= using glue for 'ns1.univie.ac.at.'
[iter]   <= using glue for 'ns9.univie.ac.at.'
[iter]   <= using glue for 'n.ns.at.'
[iter]   <= using glue for 'r.ns.at.'
[iter]   <= using glue for 'u.ns.at.'
[iter]   <= using glue for 'd.ns.at.'
[iter]   <= using glue for 'ns2.univie.ac.at.'
[iter]   <= referral response, follow
[vldr]   <= DS: OK
[vldr]   <= answer valid, OK
[resl]   <= server: '202.12.27.33' rtt: 286 ms
[resl]   <= server: '2001:500:9f::42' rtt: >=36 ms
[plan]   plan 'at.' type 'DNSKEY'
[resl]     => querying: '2001:678:d::cafe' score: 10 zone cut: 'at.' m12n: 'AT.' type: 'DNSKEY' proto: 'udp'
[iter]     <= rcode: NOERROR
[vldr]     <= parent: updating DNSKEY
[vldr]     <= answer valid, OK
[resl]     <= server: '2001:678:d::cafe' rtt: 5 ms
[resl]   => querying: '2001:678:1c::2' score: 10 zone cut: 'at.' m12n: 'AC.AT.' type: 'NS' proto: 'udp'
[iter]   <= rcode: NOERROR
[iter]   <= found cut, retrying with non-minimized name
[resl]   <= server: '2001:678:1c::2' rtt: 15 ms
[resl]   => querying: '2001:678:1c::2' score: 15 zone cut: 'at.' m12n: 'NS10.uNIvIe.ac.At.' type: 'A' proto: 'udp'
[iter]   <= using glue for 'ns7.univie.ac.at.'
[iter]   <= using glue for 'ns10.univie.ac.at.'
[iter]   <= using glue for 'ns4.univie.ac.at.'
[iter]   <= using glue for 'ns5.univie.ac.at.'
[iter]   <= using glue for 'ns3.univie.ac.at.'
[iter]   <= using glue for 'ns8.univie.ac.at.'
[iter]   <= referral response, follow
[vldr]   >< cut changed, needs revalidation
[resl]   <= server: '2001:678:1c::2' rtt: 15 ms
[plan]   plan 'univie.ac.at.' type 'DS'
[plan]     plan 'ac.at.' type 'DS'
[resl]       => querying: '2001:628:2030:4301::2' score: 10 zone cut: 'at.' m12n: 'aC.aT.' type: 'DS' proto: 'udp'
[iter]       <= rcode: NOERROR
[vldr]       <= can't prove NODATA due to optout, going insecure
[vldr]       <= DS doesn't exist, going insecure
[vldr]       <= parent: updating DS
[vldr]       <= answer valid, OK
[ pc ]       => answer cached for TTL=900
[resl]       <= server: '2001:628:2030:4301::2' rtt: 15 ms
[resl]     => querying: '2a02:568:281::130' score: 10 zone cut: 'ac.at.' m12n: 'UNIViE.Ac.at.' type: 'DS' proto: 'udp'
[iter]     <= rcode: NOERROR
[ pc ]     => answer cached for TTL=900
[resl]     <= server: '2a02:568:281::130' rtt: 19 ms
[plan]   plan 'univie.ac.at.' type 'DS'
[ pc ]     => satisfied from cache
[iter]     <= rcode: NOERROR
[vldr]     <= bogus proof of DS non-existence
[resl] finished: 8, queries: 4, mempool: 49200 B
```

```
[plan] plan 'ns10.univie.ac.at.' type 'A'
[plan]   plan 'ac.at.' type 'DS'
[ pc ]     => satisfied from cache
[iter]     <= rcode: NOERROR
[vldr]     <= DS doesn't exist, going insecure
[vldr]     <= parent: updating DS
[vldr]     <= answer valid, OK
[resl]   => querying: '2a02:568:20:1::d' score: 10 zone cut: 'ac.at.' m12n: 'UNivIe.Ac.aT.' type: 'NS' proto: 'udp'
[iter]   <= using glue for 'ns7.univie.ac.at.'
[iter]   <= using glue for 'ns8.univie.ac.at.'
[iter]   <= using glue for 'ns10.univie.ac.at.'
[iter]   <= using glue for 'ns3.univie.ac.at.'
[iter]   <= using glue for 'ns5.univie.ac.at.'
[iter]   <= using glue for 'ns4.univie.ac.at.'
[iter]   <= referral response, follow
[resl]   <= server: '2a02:568:20:1::d' rtt: 19 ms
[resl]   => querying: '2001:67c:133c::2' score: 10 zone cut: 'univie.ac.at.' m12n: 'NS10.UNIviE.Ac.At.' type: 'A' proto: 'udp'
[iter]   <= using glue for 'ns5.univie.ac.at.'
[iter]   <= using glue for 'ns3.univie.ac.at.'
[iter]   <= using glue for 'ns4.univie.ac.at.'
[iter]   <= using glue for 'ns10.univie.ac.at.'
[iter]   <= using glue for 'ns8.univie.ac.at.'
[iter]   <= using glue for 'ns7.univie.ac.at.'
[iter]   <= rcode: NOERROR
[resl]   <= server: '2001:67c:133c::2' rtt: 15 ms
[resl] finished: 4, queries: 2, mempool: 49200 B
```

**Comment by vcunat** [comment]
**Separate caches**: we already use a few cache namespaces, so it's certainly feasible, and I believe the caching part is relatively cheap here. The client-subnet changes for cache were much more complicated than this.

Adding another round-trip for "verifying" every cut isn't very nice for latency on cold cache, especially as it's common to set the child-side TTL relatively low (a few minutes).

**Comment by oerdnj** [comment]
I don't think the extra roundtrip is needed - you can just use the AUTHORITY section info when you receive it "by accident". E.g. make it an opportunistic update.

**Comment by vavrusa** [comment]
We already cache ranking, so data from authoritative answer will override data from non-authoritative answer. It's just that in default mode resolver isn't trying hard enough to ask child side about the NS set.

**Comment by vcunat** [comment]
Yes, but Fujiwara proposes AFAIK that lookups should be done based on parent-side NS/glue records, and the child-side would only be used to answer direct NS queries.

**Comment by vavrusa** [comment]
Yeah, sure it makes sense. I think it shouldn't use data with non-auth rank unless it at least tries once to fetch data with auth rank.

**Comment by stasic** [comment]
Just for the record.
Besides Fujiwara's draft and beside bind, unbound and pdns-resolver even not opensource implementations of resolver software use authoritative (600) data:
google, opendns (cisco), dyn, ultradns:
dig @google-public-dns-a.google.com +noall +answer ns10.univie.ac.at aaaa
ns10.univie.ac.at.	238	IN	AAAA	2001:67c:133c::2
dig @resolver1.opendns.com +noall +answer ns10.univie.ac.at aaaa
ns10.univie.ac.at.	371	IN	AAAA	2001:67c:133c::2
dig @rdns2.ultradns.net +noall +answer ns10.univie.ac.at aaaa
ns10.univie.ac.at.	417	IN	AAAA	2001:67c:133c::2
dig @resolver1.dyndnsinternetguide.com +noall +answer ns10.univie.ac.at aaaa
ns10.univie.ac.at.	285	IN	AAAA	2001:67c:133c::2

And even the newcomer systemd-resolved caches 600 TTL
dig @127.0.0.53 +noall +answer ns10.univie.ac.at aaaa
ns10.univie.ac.at.	524	IN	AAAA	2001:67c:133c::2

**Comment by vcunat** [comment]
This should be OK now after https://gitlab.labs.nic.cz/knot/resolver/merge_requests/269 (expected in future 1.3.0)
