### ISSUE TITLE
Error when call request.pop()

### ISSUE THREAD

**Issue by enyakucera** [CZ-NIC/knot-resolver#35]
When I call request.pop(query) from Lua module, knot show error message: “error: /usr/local/lib/kdns_modules/kres.lua:462: missing declaration for symbol ‘kr_rplan_pop'”.

My code snippet:

local function rewriteTargetAddress(state, req, ip)
    printLog(fceStartMessage .. ' "rewriteTargetAddress"...', 'debug')
    req = kres.request_t(req)

    local query = req:current()

    req:pop(query)
    req:push(ip, query.type, query.class, query.flags, 0)
    printLog(fceEndMessage .. ' "rewriteTargetAddress"...', 'debug')

    return state
end

**Comment by vcunat** [comment]
@enyakucera: thank you! You can hot-fix your installation simply by adding that line, as in 875b095, i.e. no kind of rebuild is really needed.
