### ISSUE TITLE
Update to new lua-http server API

### ISSUE THREAD

**Issue by daurnimator** [CZ-NIC/knot-resolver#36]
I noticed your http module is using the old experimental (now removed) http.server API.
There is a new api that uses an 'onstream' callback for new requests. See https://github.com/daurnimator/lua-http/blob/master/examples/server_hello.lua

**Comment by vavrusa** [comment]
Yes, it also vendors the unstable implementation. I'll rework it with the newer API.
Good to see it finalised by the way!

**Comment by oerdnj** [comment]
@vavrusa Are you able to do it soon? I would like to update lua-http in Debian to upcoming lua-http 0.1, and this would need kresd support for the new API.

**Comment by daurnimator** [comment]
Btw @vavrusa I made an effort to get rid of the h2_connection internal cq: https://github.com/daurnimator/lua-http/commit/f8cc4c8a336984fe86f8a25180cad02b267d9044

**Comment by vavrusa** [comment]
@oerdnj probably not before the holidays, this is just tidying up internals, the public API for the module is not going to change.
@daurnimator nice, the cq event loop is driven by libuv event loop in the C world, it didn't play nice with nested cqs in the previous version, hope this will work out of the box :)

**Comment by daurnimator** [comment]
> @daurnimator nice, the cq event loop is driven by libuv event loop in the C world, it didn't play nice with nested cqs in the previous version, hope this will work out of the box :)

It should do. I've written test cases for luv before without issues. If you have a sample I'd like to see it.

**Comment by vavrusa** [comment]
👏
