### ISSUE TITLE
daemon: improve tty interface

### ISSUE THREAD

**Issue by vavrusa** [CZ-NIC/knot-resolver#4]
### Problem

The CLI interface is based on reading stdin lines, not a TTY, so it doesn't support text cursor, tab completion or multiline commands. 
### Expected outcome

Basically it should behave like a Lua interpreter, but integrated in libuv loop.
There is already TTY code in libuv, and Lua interpreters around so we might want to reuse something.
- [x] Real TTY, support for arrows
- [x] Basic introspection
- [x] Tab completion

**Comment by vcunat** [comment]
`kresc` utility [is included](https://gitlab.labs.nic.cz/knot/resolver/merge_requests/177) since 1.2.5.  It's a bit beta ATM, but it supports those features.
