### ISSUE TITLE
The policy FORWARD works only with first IP when I use list of IPs for forwarding

### ISSUE THREAD

**Issue by sl-mpodlesnyi** [CZ-NIC/knot-resolver#41]
For example I set policy `policy.add(policy.all(policy.FORWARD('172.30.2.4','8.8.8.8')))`
172.30.2.4 is unreachable host
During request resolver marks first host as bad:
```[20395][wrkr]   => server: '172.30.2.4' flagged as 'bad'```
and resolver doesn't try to second dns 8.8.8.8. I am getting timeout:
```
dig @127.0.0.1 google.com

; <<>> DiG 9.11.0-P3 <<>> @127.0.0.1 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Why policy.FORWARD can have multiple IPs if it doesn't use them?

**Comment by vcunat** [comment]
This is a "duplicate" of https://gitlab.labs.nic.cz/knot/resolver/issues/125.

**Comment by vcunat** [comment]
Actually, the problem here was that you need to use braces to create a list.  Adding additional parameters to `FORWARD` does nothing.
```lua
policy.add(policy.all(policy.FORWARD({'172.30.2.4', '8.8.8.8'})))
```

**Comment by vcunat** [comment]
The issue I referenced before isn't as serious as this.
