### ISSUE TITLE
lib: implement subset of getdns API

### ISSUE THREAD

**Issue by vavrusa** [CZ-NIC/knot-resolver#5]
### Problem

I'd like the library to be reuseable by clients. [getdns](https://getdnsapi.net/) is a way to do that.
### Expected outcome
- [ ] Download the latest header
- [ ] Implement simple query resolution
- [ ] Implement basic options (TCP, EDNS...)
- [ ] Implement unit tests (some possibly exist in other implementations!)

**Comment by pspacek** [comment]
Closing things which rot here for ages now. Feel free to re-open the issue on Gitlab: https://gitlab.labs.nic.cz/knot/knot-resolver/
