### ISSUE TITLE
How can I forward all request to upstream

### ISSUE THREAD

**Issue by ookangzheng** [CZ-NIC/knot-resolver#56]
I'm using Ubuntu 18.04 64bit
I'm using Dns ove TLS
```
-- net = { net.ens160 }
net.tls('/etc/letsencrypt/live/dns.xxx.com/fullchain.pem','/etc/letsencrypt/live/dns.xxx.com/privkey.pem')
net.listen('::', 853)
net.listen('0.0.0.0', 853)
```
How can I set up all incoming request go to upstream 8.8.8.8
I can't see the example on the document
```
modules.load('policy');
-- Forward all queries (to public resolvers google DNS)
policy:add(policy.all(policy.FORWARD('8.8.8.8')))

```

**Comment by vcunat** [comment]
Yes.  Notes:
- `policy:add` is deprecated form of `policy.add`;
- `FORWARD` is clear-text (and Google doesn't support DNS over TLS, I believe).

The [documentation](http://knot-resolver.readthedocs.io/en/stable/modules.html#query-policies) does not contain this particular combination, but there are many others, along with a general description of all the filters and actions.

**Comment by ookangzheng** [comment]
For example, I forward to Quad9 9.9.9.9@853 DNS, it does support DNS over TLS
Can it work?

**Comment by vcunat** [comment]
Yes, this one IIRC:
```lua
policy.add(policy.all(policy.TLS_FORWARD({
  { '9.9.9.9', hostname = 'dns.quad9.net', ca_file = '/etc/ssl/certs/ca-bundle.crt' }
})))
```

(Adapt certificate path to your case if it doesn't match; never versions won't require you to specify it explicitly.)
