### ISSUE TITLE
Running resolver as service on macos will fail to run as a service

### ISSUE THREAD

**Issue by jaysonsantos** [CZ-NIC/knot-resolver#63]
Hey there, I am trying to use knot-resolver on macos as a service through homebrew but it fails because [stdin is /dev/null](https://github.com/Homebrew/homebrew-core/blob/master/Formula/knot-resolver.rb#L73-L74).
To reproduce it you can check with this:
```
make && sudo python -c 'import subprocess; subprocess.call(["daemon/kresd"], stdin=subprocess.DEVNULL)'
```
and this will be the output
```
[system] error error: couldn't start event poller
# I changed the code to also print the error that happened
Return of uv_strerror(ret): invalid argument%    
```

but that is funny that it only happens when install http lib with luarocks using this `luarocks --lua-dir=/usr/local/opt/lua@5.1 --tree /usr/local/ install http CRYPTO_DIR=/usr/local/opt/openssl OPENSSL_DIR=/usr/local/opt/openssl/`
i found out if i remove [this guard](https://github.com/CZ-NIC/knot-resolver/blob/v3.2.1/daemon/bindings.c#L1653-L1667) or make it go to the else it spawns the daemon fine.

Let me know if you need more information to find out what the bug is

**Comment by vcunat** [comment]
Thanks!  Removing the guard is the way to go: https://gitlab.labs.nic.cz/knot/knot-resolver/merge_requests/778

**Comment by jaysonsantos** [comment]
Cool, thank you!

**Comment by vcunat** [comment]
Merged and will be contained in future releases.
