### ISSUE TITLE
daemon: track dhcp and reconfigure as validating stub / resolver

### ISSUE THREAD

**Issue by vavrusa** [CZ-NIC/knot-resolver#7]
There should be a module to track changes in the network and environment to detect when the resolver is in an:
- Environment that blocks DNS queries altogether (and revert to stub mode)
- Environment with DNSSEC-unaware resolver (do validation)
- Open environment (full recursive resolver)

This would make it as painless as possible for the end users with frequent network transitions (hotel wifi, workplace, home, ...)

**Comment by vavrusa** [comment]
Fallback to https://github.com/fcambus/rrda if the DNS is filtered/unreachable.

**Comment by pspacek** [comment]
Moved to https://gitlab.labs.nic.cz/knot/knot-resolver/issues/244, closing.
