### ISSUE TITLE
How to build resolver in cross

### ISSUE THREAD

**Issue by micron10** [CZ-NIC/knot-resolver#70]
Hi meson build system is not friendly to build resolver in cross build
please help to cross build

**Comment by vcunat** [comment]
Hello.  I'm afraid you'll need to be more specific about what is wrong (in your case).  I'm not aware of any cross problems.

For example, we use "openwrt build system" to get 32-bit and 64-bit ARM cross (and I know about no "magic" in there): https://gitlab.nic.cz/turris/turris-os-packages/-/blob/master/net/knot-resolver/Makefile

**Comment by micron10** [comment]
Hi see the problem : 

xzcat /home/build/dl/knot-resolver-5.1.3.tar.xz | tar -C /home/build/build   -xf -
toolchain/patch-kernel.sh /home/build/build/knot-resolver-5.1.3 package/knotresolver/ knotresolver-\*.patch gnu-knotresolver-\*.patch
touch /home/build/build/knot-resolver-5.1.3/.unpacked
mkdir /home/build/build/knot-resolver-5.1.3/build; \
(cd /home/build/build/knot-resolver-5.1.3/build; \
CC=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc \
LD=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld \
CPP=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cpp \
CXX=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++ \
STRIP=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-strip \
AR=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar \
NM=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-nm \
RANLIB=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib \
OBJDUMP=/home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objdump \
CFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -I/home/build/staging/include -I/home/build/staging/usr/include" \
CPPFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -I/home/build/staging/include -I/home/build/staging/usr/include" \
LDFLAGS="-L/home/build/staging/lib -L/home/build/staging/usr/lib -lncurses -ltinfo -liconv -lz -lgnutls -lz -liconv -lnettle -lgmp -lidn -lidn2 -lssl -lcrypto -lp11-kit -lhogweed -lffi -ljansson -lm -lcap-ng -ldl -lpthread -lurcu -lurcu-common -luv -lknot -ldnssec -lzscanner -lluajit -ledit -llmdb" \
libknot_CFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -flto -I/home/build/staging/include -I/home/build/staging/usr/include" \
libuv_CFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -flto -I/home/build/staging/include -I/home/build/staging/usr/include" \
lua_CFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -flto -I/home/build/staging/include -I/home/build/staging/usr/include" \
libzscanner_CFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -flto -I/home/build/staging/include -I/home/build/staging/usr/include" \
libdnssec_CFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -flto -I/home/build/staging/include -I/home/build/staging/usr/include" \
libsystemd_CFLAGS="-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -flto -I/home/build/staging/include -I/home/build/staging/usr/include" \
libknot_LIBS="-L/home/build/staging/lib -L/home/build/staging/usr/lib -lknot -ldnssec -lcap-ng" \
libuv_LIBS="-L/home/build/staging/lib -L/home/build/staging/usr/lib -luv" \
libdnssec_LIBS="-L/home/build/staging/lib -L/home/build/staging/usr/lib" \
libzscanner_LIBS="-L/home/build/staging/lib -L/home/build/staging/usr/lib -lzscanner" \
libsystemd_LIBS="-L/home/build/staging/lib -L/home/build/staging/usr/lib" \
lua_LIBS="-L/home/build/staging/lib -L/home/build/staging/usr/lib" \
HAS_libuv=yes \
HAS_gnutls=yes \
HAS_go=no \
HAS_libsystemd=no \
LIBDIR="-L/home/build/staging/lib -L/home/build/staging/usr/lib -lncurses -ltinfo -liconv -lz -lgnutls -lz -liconv -lnettle -lgmp -lidn -lidn2 -lssl -lcrypto -lp11-kit -lhogweed -lffi -ljansson -lm -lcap-ng -ldl -lpthread -lurcu -lurcu-common -luv -lknot -ldnssec -lzscanner -lluajit -ledit -llmdb" \
LIBRARY_PATH="-L/home/build/staging/lib -L/home/build/staging/usr/lib -lncurses -ltinfo -liconv -lz -lgnutls -lz -liconv -lnettle -lgmp -lidn -lidn2 -lssl -lcrypto -lp11-kit -lhogweed -lffi -ljansson -lm -lcap-ng -ldl -lpthread -lurcu -lurcu-common -luv -lknot -ldnssec -lzscanner -lluajit -ledit -llmdb" \
meson \
--prefix=/usr \
--buildtype=release \
-DCROSS=1 \
.. \
)
The Meson build system
Version: 0.53.2
Source dir: /home/build/build/knot-resolver-5.1.3
Build dir: /home/build/build/knot-resolver-5.1.3/build
Build type: native build
WARNING: Unknown options: "CROSS"
Project name: knot-resolver
Project version: 5.1.3
Appending CFLAGS from environment: '-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -I/home/build/staging/include -I/home/build/staging/usr/include'
Appending LDFLAGS from environment: ['-L/home/build/staging/lib', '-L/home/build/staging/usr/lib', '-lncurses', '-ltinfo', '-liconv', '-lz', '-lgnutls', '-lz', '-liconv', '-lnettle', '-lgmp', '-lidn', '-lidn2', '-lssl', '-lcrypto', '-lp11-kit', '-lhogweed', '-lffi', '-ljansson', '-lm', '-lcap-ng', '-ldl', '-lpthread', '-lurcu', '-lurcu-common', '-luv', '-lknot', '-ldnssec', '-lzscanner', '-lluajit', '-ledit', '-llmdb']
Appending CPPFLAGS from environment: '-pipe -O3 -Wall -march=skylake -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-stack-protector -mno-stackrealign -I/home/build/staging/include -I/home/build/staging/usr/include'
/home/build/build/knot-resolver-5.1.3/build/meson-private/sanitycheckc.exe: error while loading shared libraries: libknot.so.11: cannot open shared object file: No such file or directory

meson.build:3:0: ERROR: Executables created by c compiler /home/build/build/ct/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc are not runnable.

A full log can be found at /home/build/build/knot-resolver-5.1.3/build/meson-logs/meson-log.txt
make[2]: [package/knotresolver/knotresolver.mk:54: /home/build/build/knot-resolver-5.1.3/.configured] Error 1 (ignored)


The problem is in meson.
Meson get lib from system lib not from crossbuild lib .

**Comment by vcunat** [comment]
Well, I've never had reason to do a Windows->Linux cross so far, but my approach would generally be to first try the approaches that meson documents instead of hand-rolling it: https://mesonbuild.com/Cross-compilation.html#starting-a-cross-build

**Comment by vcunat** [comment]
In particular, note your output has `Build type: native build`, so meson even haven't noticed you want a cross build.

**Comment by vcunat** [comment]
A successful snippet looks more like
```
The Meson build system
Version: 0.55.1
Source dir: /build/knot-resolver-5.1.3
Build dir: /build/knot-resolver-5.1.3/build
Build type: cross build
Using 'PKG_CONFIG_PATH' from environment with value: foo bar
Project name: knot-resolver
Project version: 5.1.3
Using 'CC_FOR_BUILD' from environment with value: 'gcc'
C compiler for the build machine: gcc (gcc 9.3.0 "gcc (GCC) 9.3.0")
C linker for the build machine: gcc ld.bfd 2.31.1
Using 'AR_FOR_BUILD' from environment with value: 'ar'
Using 'CXX_FOR_BUILD' from environment with value: 'g++'
C++ compiler for the build machine: g++ (gcc 9.3.0 "g++ (GCC) 9.3.0")
C++ linker for the build machine: g++ ld.bfd 2.31.1
Using 'CC' from environment with value: 'aarch64-unknown-linux-gnu-gcc'
C compiler for the host machine: aarch64-unknown-linux-gnu-gcc (gcc 9.3.0 "aarch64-unknown-linux-gnu-gcc (GCC) 9.3.0")
C linker for the host machine: aarch64-unknown-linux-gnu-gcc ld.bfd 2.31.1
Using 'AR' from environment with value: 'aarch64-unknown-linux-gnu-ar'
Using 'CXX' from environment with value: 'aarch64-unknown-linux-gnu-g++'
C++ compiler for the host machine: aarch64-unknown-linux-gnu-g++ (gcc 9.3.0 "aarch64-unknown-linux-gnu-g++ (GCC) 9.3.0")
C++ linker for the host machine: aarch64-unknown-linux-gnu-g++ ld.bfd 2.31.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: aarch64
Host machine cpu: aarch64
Target machine cpu family: aarch64
Target machine cpu: aarch64
Message: --- required dependencies ---
```

**Comment by micron10** [comment]
how to notice meson is this cross build not native.

With old versikn when use configure and make build is ok
when switch to meson have this problem
May be need to set in meson build is this cross build.

**Comment by vcunat** [comment]
Well yes... you can't build by the same command as before our switch to meson, but it should be simpler and less error-prone than before.  I think meson notices the intention from the `--cross-file` option :-)  but I'd just try following instructions in the docs link above. 

I haven't needed to really read those myself so far.  Instead I followed distribution/packaging systems instructions and they did the meson-specific stuff for me, but I'm not aware of such for Windows.  (They were NixPkgs and OpenWrt/Turris, in my cases.)

**Comment by micron10** [comment]
thanks !!
after make cross-file and put to meson all work fine
Thanks

На пн, 19.10.2020 г. в 14:04 Vladimír Čunát <notifications@github.com>
написа:
