### ISSUE TITLE
Compilation problem when DOH2 not enable

### ISSUE THREAD

**Issue by realPy** [CZ-NIC/knot-resolver#72]
If DOH2 not enable http_free_headers is not declared but worker.c use it

https://github.com/CZ-NIC/knot-resolver/blob/299b6ca853551f7ee235b23405f0dd78f7694d81/daemon/worker.c#L1743

**Comment by vcunat** [comment]
Thanks, I see.  We'll fix it.

**Comment by realPy** [comment]
Oh thks , just se that repo is just a mirror, i'll begin to open issue in the gitlab.

**Comment by vcunat** [comment]
I'll open a merge request in a few minutes anyway.

**Comment by vcunat** [comment]
https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/1197
