### ISSUE TITLE
Possible hack? Your websites are all down

### ISSUE THREAD

**Issue by elandorr** [CZ-NIC/knot-resolver#73]
https://www.knot-dns.cz/ is a literal 404.

The gitlab is dead too.

Posting here since this may be the only way you can see it if the infra is dead.

**Comment by elandorr** [comment]
I must've hit the jackpot then to just visit right now. Good luck getting it back up!

**Comment by vcunat** [comment]
It should be up for some time now, though perhaps some parts not in perfect state.
