### ISSUE TITLE
In doh2 mode, the response is Wrong

### ISSUE THREAD

**Issue by ShipeiXu** [CZ-NIC/knot-resolver#79]
As shown below, The addition area of the response packet is very large. has a lot of padding bytes
<img width="855" alt="image" src="https://user-images.githubusercontent.com/3360832/177499117-ea9b379e-ff1e-464c-87ce-3a727109f401.png">
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/3360832/177499325-379c588c-c389-44b3-a1ff-b18f321c621f.png">

**Comment by ShipeiXu** [comment]
config:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/3360832/177499531-fca1c449-e46a-4fdc-b351-3fa59acb75cb.png">

**Comment by vcunat** [comment]
Yes, that's not wrong, it's an intentional privacy feature.  The main point of the DoH standard was privacy, and message size is a part of that.

You can find more information about padding around RFCs like https://www.rfc-editor.org/rfc/rfc8467.html

**Comment by ShipeiXu** [comment]
Bug，this increases the amplification attack。

**Comment by vcunat** [comment]
Amplification is only considered for reflection attacks, i.e. when source address is spoofed to another network path.  That is not possible with DoH (or DoT).
