### ISSUE TITLE
@alesmrazek github GPG keys

### ISSUE THREAD

**Issue by daurnimator** [CZ-NIC/knot-resolver#82]
@alesmrazek it appears as though you have changed GPG keys (to 3057EE9A448F362D74205A779AB120DA0A76F6DE) but have not updated your github profile (or easily made that key available).

This results in the github UI looking like e.g.
![image](https://user-images.githubusercontent.com/127971/185289035-898751b8-2657-4dfd-a575-ef5535bbf22b.png)

![image](https://user-images.githubusercontent.com/127971/185289071-b92c9305-a50e-4309-958f-34ec23d0ec21.png)

Please:
  - Make this new key available somewhere (e.g. push to keyservers)
  - Confirm that this new key is you (using your old key to sign new one is best method)
  - Upload your new key to github so that the UI is fixed

**Comment by vcunat** [comment]
I can see the key on keys.openpgp.org (at least now).  We also had it on https://www.knot-resolver.cz/download/ all the time.

**Comment by alesmrazek** [comment]
I uploaded the public key to the github account so everything should be verified now. I am sorry for that.
